config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :shops
  resources :products
  root 'shops#index'
  resources :charges
  get 'order/myorder'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :shop, dependent: :destroy
end

app/models/shop.rb
class Shop < ApplicationRecord
	has_many :products, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
	end

	def create
	  # Amount in cents
	  @amount = 500

	  customer = Stripe::Customer.create(
	    :email => params[:stripeEmail],
	    :source  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount,
	    :description => 'Rails Stripe customer',
	    :currency    => 'usd'
	  )

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to new_charge_path
	end
end 

app/controllers/order_controller.rb
class OrderController < ApplicationController

  def myorder
	 OrderMailer.order_created(current_user).deliver_now
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @products = Product.find_by(id: params[:id])
    @shop = @products.shop
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :quantity, :price)
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
    @shop = Shop.find_by(id: params[:id])
    @product = @shop.products
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
	  <article>
	    <% if flash[:error].present? %>
	      <div id="error_explanation">
		<p><%= flash[:error] %></p>
	      </div>
	    <% end %>
	    <label class="amount">
	      <span>Amount: $5.00</span>
	    </label>
	  </article>

	  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
		  data-description="A month's subscription"
		  data-amount="500"
		  data-locale="auto"></script>
	<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
   <% if user_signed_in? %>

    Signed in as <%= current_user.email %>.
  Not you?

    <%= link_to "Sign out",
  destroy_user_session_path, :method => :delete %>

  <% else %>

    <%= link_to "Sign up",
  new_user_registration_path %> or <%= link_to "sign in",
  new_user_session_path %>

  <% end %> 

  <body>
    <%= yield %>
  </body>
</html>

app/views/order/myorder.html.erb
<h1>hii!  Your order created successfully </h1>

<%= link_to 'Back', shops_path, class:"btn btn-success btn-sm" %>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity, id: :product_quantity %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :product_price %>
  </div>

  <p>
    <br>
     <%= form.select :shop_id, Shop.all.map{|m| [m.name, m.id] },{prompt: "Please select Shop"}, class: "form-control", :null => false %>
  </p>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>S.No.</th>
      <th>Name</th>
      <th>Quantity</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each_with_index do |product,index| %>
      <tr>
        <td><%= index + 1 %>.</td>
        <td><%= product.name %></td>
        <td><%= product.quantity %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product, class:"btn btn-success btn-sm" %></td>
        <td><%= link_to 'Edit', edit_product_path(product), class:"btn btn-primary btn-sm" %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path, class:"btn btn-primary btn-sm" %> | 
<%= link_to 'Back', root_path, class:"btn btn-success btn-sm" %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path, class:"btn btn-success btn-sm" %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product), class:"btn btn-success btn-sm" %> |
<%= link_to 'Back', products_path, class:"btn btn-primary btn-sm" %> | 
<%= link_to 'Place Order', order_myorder_path, class:"btn btn-success btn-sm" %>

app/views/shops/_form.html.erb
<%= form_with(model: shop, local: true) do |form| %>
  <% if shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :shop_name %>
    <%= form.text_field :name %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>Editing Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Show', @shop, class:"btn btn-success btn-sm" %> |
<%= link_to 'Back', shops_path, class:"btn btn-primary btn-sm" %>

app/views/shops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shops</h1>

<table>
  <thead>
    <tr>
      <th>S.No.</th>
      <th>Shops</th>
     <!--  <th>Product name</th>
      <th>Quantity</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each_with_index do |shop,index| %>
      <tr>
        <td><%= index + 1 %>.</td>
        <td><%= shop.name %></td>
        <td><%#= shop.product_id %></td>
        <td><%#= shop.product_name %></td>
        <td><%#= shop.quantity %></td>
        <td><%= link_to 'Show', shop, class:"btn btn-info btn-sm" %> | </td> 
        <td><%= link_to 'Edit', edit_shop_path(shop), class:"btn btn-primary btn-sm" %> | </td>
        <td><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop', new_shop_path, class:"btn btn-success btn-sm" %> | 
<%= link_to 'New Product', new_product_path, class:"btn btn-primary btn-sm" %>

<%#= link_to 'payment', new_charge_path %>

app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shop Name:</strong>
  <%= @shop.name %>
</p>
<h1>Products</h1>
<p>
	<strong>Product Name:</strong>
  <%= @product.try(:name) %>
</p>

<p>
	<strong>Quantity:</strong>
  <%= @product.try(:quantity) %>
</p>

<p>
	<strong>Price:</strong>
  <%= @product.try(:price) %>
</p>

<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>